/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var a=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var d=Object.prototype.hasOwnProperty;var h=(o,n)=>{for(var e in n)a(o,e,{get:n[e],enumerable:!0})},g=(o,n,e,t)=>{if(n&&typeof n=="object"||typeof n=="function")for(let l of m(n))!d.call(o,l)&&l!==e&&a(o,l,{get:()=>n[l],enumerable:!(t=r(n,l))||t.enumerable});return o};var u=o=>g(a({},"__esModule",{value:!0}),o);var C={};h(C,{default:()=>s});module.exports=u(C);var c=require("obsidian"),s=class extends c.Plugin{async onload(){this.addCommand({id:"new-line-above",name:"Above",icon:"move-up-left",editorCallback:n=>{let e=n.getCursor(),l=n.getLine(e.line).match(/^\s*(- \[[x ]\]|[+*-]|[0-9]+\.)\s+/),i=l?l[0]:"";n.replaceRange(`${i}
`,{line:e.line,ch:0}),n.setCursor(e.line,i.length)}}),this.addCommand({id:"new-line-below",name:"Below",icon:"move-down-left",editorCallback:n=>{let e=n.getCursor(),t=n.getLine(e.line),l=t.match(/^\s*(- \[[x ]\]|[+*-]|[0-9]+\.)\s+/),i=l?l[0]:"";n.replaceRange(`
${i}`,{line:e.line,ch:t.length}),n.setCursor(e.line+1,i.length)}})}onunload(){}};

/* nosourcemap */